/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: StackRPC.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "StackRPC.pb-c.h"
void   stack_rpc__v1__control_request__init
                     (StackRPC__V1__ControlRequest         *message)
{
  static const StackRPC__V1__ControlRequest init_value = STACK_RPC__V1__CONTROL_REQUEST__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__control_request__get_packed_size
                     (const StackRPC__V1__ControlRequest *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__control_request__pack
                     (const StackRPC__V1__ControlRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__control_request__pack_to_buffer
                     (const StackRPC__V1__ControlRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__ControlRequest *
       stack_rpc__v1__control_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__ControlRequest *)
     protobuf_c_message_unpack (&stack_rpc__v1__control_request__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__control_request__free_unpacked
                     (StackRPC__V1__ControlRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__control_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__control_response__init
                     (StackRPC__V1__ControlResponse         *message)
{
  static const StackRPC__V1__ControlResponse init_value = STACK_RPC__V1__CONTROL_RESPONSE__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__control_response__get_packed_size
                     (const StackRPC__V1__ControlResponse *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__control_response__pack
                     (const StackRPC__V1__ControlResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__control_response__pack_to_buffer
                     (const StackRPC__V1__ControlResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__control_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__ControlResponse *
       stack_rpc__v1__control_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__ControlResponse *)
     protobuf_c_message_unpack (&stack_rpc__v1__control_response__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__control_response__free_unpacked
                     (StackRPC__V1__ControlResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__control_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__cue_action_request__init
                     (StackRPC__V1__CueActionRequest         *message)
{
  static const StackRPC__V1__CueActionRequest init_value = STACK_RPC__V1__CUE_ACTION_REQUEST__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__cue_action_request__get_packed_size
                     (const StackRPC__V1__CueActionRequest *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__cue_action_request__pack
                     (const StackRPC__V1__CueActionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__cue_action_request__pack_to_buffer
                     (const StackRPC__V1__CueActionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__CueActionRequest *
       stack_rpc__v1__cue_action_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__CueActionRequest *)
     protobuf_c_message_unpack (&stack_rpc__v1__cue_action_request__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__cue_action_request__free_unpacked
                     (StackRPC__V1__CueActionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__cue_action_response__init
                     (StackRPC__V1__CueActionResponse         *message)
{
  static const StackRPC__V1__CueActionResponse init_value = STACK_RPC__V1__CUE_ACTION_RESPONSE__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__cue_action_response__get_packed_size
                     (const StackRPC__V1__CueActionResponse *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__cue_action_response__pack
                     (const StackRPC__V1__CueActionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__cue_action_response__pack_to_buffer
                     (const StackRPC__V1__CueActionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__CueActionResponse *
       stack_rpc__v1__cue_action_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__CueActionResponse *)
     protobuf_c_message_unpack (&stack_rpc__v1__cue_action_response__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__cue_action_response__free_unpacked
                     (StackRPC__V1__CueActionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__cue_action_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__list_cues_request__init
                     (StackRPC__V1__ListCuesRequest         *message)
{
  static const StackRPC__V1__ListCuesRequest init_value = STACK_RPC__V1__LIST_CUES_REQUEST__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__list_cues_request__get_packed_size
                     (const StackRPC__V1__ListCuesRequest *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__list_cues_request__pack
                     (const StackRPC__V1__ListCuesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__list_cues_request__pack_to_buffer
                     (const StackRPC__V1__ListCuesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__ListCuesRequest *
       stack_rpc__v1__list_cues_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__ListCuesRequest *)
     protobuf_c_message_unpack (&stack_rpc__v1__list_cues_request__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__list_cues_request__free_unpacked
                     (StackRPC__V1__ListCuesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__list_cues_response__init
                     (StackRPC__V1__ListCuesResponse         *message)
{
  static const StackRPC__V1__ListCuesResponse init_value = STACK_RPC__V1__LIST_CUES_RESPONSE__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__list_cues_response__get_packed_size
                     (const StackRPC__V1__ListCuesResponse *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__list_cues_response__pack
                     (const StackRPC__V1__ListCuesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__list_cues_response__pack_to_buffer
                     (const StackRPC__V1__ListCuesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__ListCuesResponse *
       stack_rpc__v1__list_cues_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__ListCuesResponse *)
     protobuf_c_message_unpack (&stack_rpc__v1__list_cues_response__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__list_cues_response__free_unpacked
                     (StackRPC__V1__ListCuesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__list_cues_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__get_cues_request__init
                     (StackRPC__V1__GetCuesRequest         *message)
{
  static const StackRPC__V1__GetCuesRequest init_value = STACK_RPC__V1__GET_CUES_REQUEST__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__get_cues_request__get_packed_size
                     (const StackRPC__V1__GetCuesRequest *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__get_cues_request__pack
                     (const StackRPC__V1__GetCuesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__get_cues_request__pack_to_buffer
                     (const StackRPC__V1__GetCuesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__GetCuesRequest *
       stack_rpc__v1__get_cues_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__GetCuesRequest *)
     protobuf_c_message_unpack (&stack_rpc__v1__get_cues_request__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__get_cues_request__free_unpacked
                     (StackRPC__V1__GetCuesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__get_cues_response__init
                     (StackRPC__V1__GetCuesResponse         *message)
{
  static const StackRPC__V1__GetCuesResponse init_value = STACK_RPC__V1__GET_CUES_RESPONSE__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__get_cues_response__get_packed_size
                     (const StackRPC__V1__GetCuesResponse *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__get_cues_response__pack
                     (const StackRPC__V1__GetCuesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__get_cues_response__pack_to_buffer
                     (const StackRPC__V1__GetCuesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__GetCuesResponse *
       stack_rpc__v1__get_cues_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__GetCuesResponse *)
     protobuf_c_message_unpack (&stack_rpc__v1__get_cues_response__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__get_cues_response__free_unpacked
                     (StackRPC__V1__GetCuesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__get_cues_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__get_show_request__init
                     (StackRPC__V1__GetShowRequest         *message)
{
  static const StackRPC__V1__GetShowRequest init_value = STACK_RPC__V1__GET_SHOW_REQUEST__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__get_show_request__get_packed_size
                     (const StackRPC__V1__GetShowRequest *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__get_show_request__pack
                     (const StackRPC__V1__GetShowRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__get_show_request__pack_to_buffer
                     (const StackRPC__V1__GetShowRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__GetShowRequest *
       stack_rpc__v1__get_show_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__GetShowRequest *)
     protobuf_c_message_unpack (&stack_rpc__v1__get_show_request__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__get_show_request__free_unpacked
                     (StackRPC__V1__GetShowRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__get_show_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__get_show_response__init
                     (StackRPC__V1__GetShowResponse         *message)
{
  static const StackRPC__V1__GetShowResponse init_value = STACK_RPC__V1__GET_SHOW_RESPONSE__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__get_show_response__get_packed_size
                     (const StackRPC__V1__GetShowResponse *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__get_show_response__pack
                     (const StackRPC__V1__GetShowResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__get_show_response__pack_to_buffer
                     (const StackRPC__V1__GetShowResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__get_show_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__GetShowResponse *
       stack_rpc__v1__get_show_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__GetShowResponse *)
     protobuf_c_message_unpack (&stack_rpc__v1__get_show_response__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__get_show_response__free_unpacked
                     (StackRPC__V1__GetShowResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__get_show_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stack_rpc__v1__cue_info__init
                     (StackRPC__V1__CueInfo         *message)
{
  static const StackRPC__V1__CueInfo init_value = STACK_RPC__V1__CUE_INFO__INIT;
  *message = init_value;
}
size_t stack_rpc__v1__cue_info__get_packed_size
                     (const StackRPC__V1__CueInfo *message)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stack_rpc__v1__cue_info__pack
                     (const StackRPC__V1__CueInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stack_rpc__v1__cue_info__pack_to_buffer
                     (const StackRPC__V1__CueInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &stack_rpc__v1__cue_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StackRPC__V1__CueInfo *
       stack_rpc__v1__cue_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StackRPC__V1__CueInfo *)
     protobuf_c_message_unpack (&stack_rpc__v1__cue_info__descriptor,
                                allocator, len, data);
}
void   stack_rpc__v1__cue_info__free_unpacked
                     (StackRPC__V1__CueInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &stack_rpc__v1__cue_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor stack_rpc__v1__control_request__field_descriptors[5] =
{
  {
    "message_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__ControlRequest, message_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cue_action_request",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlRequest, type_case),
    offsetof(StackRPC__V1__ControlRequest, cue_action_request),
    &stack_rpc__v1__cue_action_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_cues_request",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlRequest, type_case),
    offsetof(StackRPC__V1__ControlRequest, list_cues_request),
    &stack_rpc__v1__list_cues_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_cues_request",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlRequest, type_case),
    offsetof(StackRPC__V1__ControlRequest, get_cues_request),
    &stack_rpc__v1__get_cues_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_show_request",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlRequest, type_case),
    offsetof(StackRPC__V1__ControlRequest, get_show_request),
    &stack_rpc__v1__get_show_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__control_request__field_indices_by_name[] = {
  1,   /* field[1] = cue_action_request */
  3,   /* field[3] = get_cues_request */
  4,   /* field[4] = get_show_request */
  2,   /* field[2] = list_cues_request */
  0,   /* field[0] = message_id */
};
static const ProtobufCIntRange stack_rpc__v1__control_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__control_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.ControlRequest",
  "ControlRequest",
  "StackRPC__V1__ControlRequest",
  "StackRPC.v1",
  sizeof(StackRPC__V1__ControlRequest),
  5,
  stack_rpc__v1__control_request__field_descriptors,
  stack_rpc__v1__control_request__field_indices_by_name,
  1,  stack_rpc__v1__control_request__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__control_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__control_response__field_descriptors[5] =
{
  {
    "response_to",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__ControlResponse, response_to),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cue_action_response",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlResponse, type_case),
    offsetof(StackRPC__V1__ControlResponse, cue_action_response),
    &stack_rpc__v1__cue_action_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list_cues_response",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlResponse, type_case),
    offsetof(StackRPC__V1__ControlResponse, list_cues_response),
    &stack_rpc__v1__list_cues_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_cues_response",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlResponse, type_case),
    offsetof(StackRPC__V1__ControlResponse, get_cues_response),
    &stack_rpc__v1__get_cues_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "get_show_response",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__ControlResponse, type_case),
    offsetof(StackRPC__V1__ControlResponse, get_show_response),
    &stack_rpc__v1__get_show_response__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__control_response__field_indices_by_name[] = {
  1,   /* field[1] = cue_action_response */
  3,   /* field[3] = get_cues_response */
  4,   /* field[4] = get_show_response */
  2,   /* field[2] = list_cues_response */
  0,   /* field[0] = response_to */
};
static const ProtobufCIntRange stack_rpc__v1__control_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__control_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.ControlResponse",
  "ControlResponse",
  "StackRPC__V1__ControlResponse",
  "StackRPC.v1",
  sizeof(StackRPC__V1__ControlResponse),
  5,
  stack_rpc__v1__control_response__field_descriptors,
  stack_rpc__v1__control_response__field_indices_by_name,
  1,  stack_rpc__v1__control_response__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__control_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__cue_action_request__field_descriptors[2] =
{
  {
    "cue_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueActionRequest, cue_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cue_action",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueActionRequest, cue_action),
    &stack_rpc__v1__cue_action__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__cue_action_request__field_indices_by_name[] = {
  1,   /* field[1] = cue_action */
  0,   /* field[0] = cue_id */
};
static const ProtobufCIntRange stack_rpc__v1__cue_action_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__cue_action_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueActionRequest",
  "CueActionRequest",
  "StackRPC__V1__CueActionRequest",
  "StackRPC.v1",
  sizeof(StackRPC__V1__CueActionRequest),
  2,
  stack_rpc__v1__cue_action_request__field_descriptors,
  stack_rpc__v1__cue_action_request__field_indices_by_name,
  1,  stack_rpc__v1__cue_action_request__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__cue_action_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define stack_rpc__v1__cue_action_response__field_descriptors NULL
#define stack_rpc__v1__cue_action_response__field_indices_by_name NULL
#define stack_rpc__v1__cue_action_response__number_ranges NULL
const ProtobufCMessageDescriptor stack_rpc__v1__cue_action_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueActionResponse",
  "CueActionResponse",
  "StackRPC__V1__CueActionResponse",
  "StackRPC.v1",
  sizeof(StackRPC__V1__CueActionResponse),
  0,
  stack_rpc__v1__cue_action_response__field_descriptors,
  stack_rpc__v1__cue_action_response__field_indices_by_name,
  0,  stack_rpc__v1__cue_action_response__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__cue_action_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__list_cues_request__field_descriptors[1] =
{
  {
    "include_children",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__ListCuesRequest, include_children),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__list_cues_request__field_indices_by_name[] = {
  0,   /* field[0] = include_children */
};
static const ProtobufCIntRange stack_rpc__v1__list_cues_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__list_cues_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.ListCuesRequest",
  "ListCuesRequest",
  "StackRPC__V1__ListCuesRequest",
  "StackRPC.v1",
  sizeof(StackRPC__V1__ListCuesRequest),
  1,
  stack_rpc__v1__list_cues_request__field_descriptors,
  stack_rpc__v1__list_cues_request__field_indices_by_name,
  1,  stack_rpc__v1__list_cues_request__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__list_cues_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__list_cues_response__field_descriptors[1] =
{
  {
    "cue_uid",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(StackRPC__V1__ListCuesResponse, n_cue_uid),
    offsetof(StackRPC__V1__ListCuesResponse, cue_uid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__list_cues_response__field_indices_by_name[] = {
  0,   /* field[0] = cue_uid */
};
static const ProtobufCIntRange stack_rpc__v1__list_cues_response__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__list_cues_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.ListCuesResponse",
  "ListCuesResponse",
  "StackRPC__V1__ListCuesResponse",
  "StackRPC.v1",
  sizeof(StackRPC__V1__ListCuesResponse),
  1,
  stack_rpc__v1__list_cues_response__field_descriptors,
  stack_rpc__v1__list_cues_response__field_indices_by_name,
  1,  stack_rpc__v1__list_cues_response__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__list_cues_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__get_cues_request__field_descriptors[1] =
{
  {
    "cue_uid",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(StackRPC__V1__GetCuesRequest, n_cue_uid),
    offsetof(StackRPC__V1__GetCuesRequest, cue_uid),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__get_cues_request__field_indices_by_name[] = {
  0,   /* field[0] = cue_uid */
};
static const ProtobufCIntRange stack_rpc__v1__get_cues_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__get_cues_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.GetCuesRequest",
  "GetCuesRequest",
  "StackRPC__V1__GetCuesRequest",
  "StackRPC.v1",
  sizeof(StackRPC__V1__GetCuesRequest),
  1,
  stack_rpc__v1__get_cues_request__field_descriptors,
  stack_rpc__v1__get_cues_request__field_indices_by_name,
  1,  stack_rpc__v1__get_cues_request__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__get_cues_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__get_cues_response__field_descriptors[1] =
{
  {
    "cue_info",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(StackRPC__V1__GetCuesResponse, n_cue_info),
    offsetof(StackRPC__V1__GetCuesResponse, cue_info),
    &stack_rpc__v1__cue_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__get_cues_response__field_indices_by_name[] = {
  0,   /* field[0] = cue_info */
};
static const ProtobufCIntRange stack_rpc__v1__get_cues_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__get_cues_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.GetCuesResponse",
  "GetCuesResponse",
  "StackRPC__V1__GetCuesResponse",
  "StackRPC.v1",
  sizeof(StackRPC__V1__GetCuesResponse),
  1,
  stack_rpc__v1__get_cues_response__field_descriptors,
  stack_rpc__v1__get_cues_response__field_indices_by_name,
  1,  stack_rpc__v1__get_cues_response__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__get_cues_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define stack_rpc__v1__get_show_request__field_descriptors NULL
#define stack_rpc__v1__get_show_request__field_indices_by_name NULL
#define stack_rpc__v1__get_show_request__number_ranges NULL
const ProtobufCMessageDescriptor stack_rpc__v1__get_show_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.GetShowRequest",
  "GetShowRequest",
  "StackRPC__V1__GetShowRequest",
  "StackRPC.v1",
  sizeof(StackRPC__V1__GetShowRequest),
  0,
  stack_rpc__v1__get_show_request__field_descriptors,
  stack_rpc__v1__get_show_request__field_indices_by_name,
  0,  stack_rpc__v1__get_show_request__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__get_show_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__get_show_response__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__GetShowResponse, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "designer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__GetShowResponse, designer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__GetShowResponse, revision),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filename",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__GetShowResponse, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__get_show_response__field_indices_by_name[] = {
  1,   /* field[1] = designer */
  3,   /* field[3] = filename */
  0,   /* field[0] = name */
  2,   /* field[2] = revision */
};
static const ProtobufCIntRange stack_rpc__v1__get_show_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__get_show_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.GetShowResponse",
  "GetShowResponse",
  "StackRPC__V1__GetShowResponse",
  "StackRPC.v1",
  sizeof(StackRPC__V1__GetShowResponse),
  4,
  stack_rpc__v1__get_show_response__field_descriptors,
  stack_rpc__v1__get_show_response__field_indices_by_name,
  1,  stack_rpc__v1__get_show_response__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__get_show_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stack_rpc__v1__cue_info__field_descriptors[11] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_uid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, parent_uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, state),
    &stack_rpc__v1__cue_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prewait_time",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, prewait_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action_time",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, action_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postwait_time",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, postwait_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post_trigger",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, post_trigger),
    &stack_rpc__v1__cue_wait_trigger__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "colour",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, colour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notes",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(StackRPC__V1__CueInfo, notes),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stack_rpc__v1__cue_info__field_indices_by_name[] = {
  6,   /* field[6] = action_time */
  9,   /* field[9] = colour */
  2,   /* field[2] = id */
  4,   /* field[4] = name */
  10,   /* field[10] = notes */
  1,   /* field[1] = parent_uid */
  8,   /* field[8] = post_trigger */
  7,   /* field[7] = postwait_time */
  5,   /* field[5] = prewait_time */
  3,   /* field[3] = state */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange stack_rpc__v1__cue_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor stack_rpc__v1__cue_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueInfo",
  "CueInfo",
  "StackRPC__V1__CueInfo",
  "StackRPC.v1",
  sizeof(StackRPC__V1__CueInfo),
  11,
  stack_rpc__v1__cue_info__field_descriptors,
  stack_rpc__v1__cue_info__field_indices_by_name,
  1,  stack_rpc__v1__cue_info__number_ranges,
  (ProtobufCMessageInit) stack_rpc__v1__cue_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue stack_rpc__v1__cue_action__enum_values_by_number[4] =
{
  { "Play", "STACK_RPC__V1__CUE_ACTION__Play", 0 },
  { "Pause", "STACK_RPC__V1__CUE_ACTION__Pause", 1 },
  { "Stop", "STACK_RPC__V1__CUE_ACTION__Stop", 2 },
  { "StopAll", "STACK_RPC__V1__CUE_ACTION__StopAll", 3 },
};
static const ProtobufCIntRange stack_rpc__v1__cue_action__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex stack_rpc__v1__cue_action__enum_values_by_name[4] =
{
  { "Pause", 1 },
  { "Play", 0 },
  { "Stop", 2 },
  { "StopAll", 3 },
};
const ProtobufCEnumDescriptor stack_rpc__v1__cue_action__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueAction",
  "CueAction",
  "StackRPC__V1__CueAction",
  "StackRPC.v1",
  4,
  stack_rpc__v1__cue_action__enum_values_by_number,
  4,
  stack_rpc__v1__cue_action__enum_values_by_name,
  1,
  stack_rpc__v1__cue_action__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue stack_rpc__v1__cue_state__enum_values_by_number[7] =
{
  { "Error", "STACK_RPC__V1__CUE_STATE__Error", -1 },
  { "Stopped", "STACK_RPC__V1__CUE_STATE__Stopped", 0 },
  { "Paused", "STACK_RPC__V1__CUE_STATE__Paused", 1 },
  { "Prepared", "STACK_RPC__V1__CUE_STATE__Prepared", 2 },
  { "PlayingPre", "STACK_RPC__V1__CUE_STATE__PlayingPre", 3 },
  { "PlayingAction", "STACK_RPC__V1__CUE_STATE__PlayingAction", 4 },
  { "PlayingPost", "STACK_RPC__V1__CUE_STATE__PlayingPost", 5 },
};
static const ProtobufCIntRange stack_rpc__v1__cue_state__value_ranges[] = {
{-1, 0},{0, 7}
};
static const ProtobufCEnumValueIndex stack_rpc__v1__cue_state__enum_values_by_name[7] =
{
  { "Error", 0 },
  { "Paused", 2 },
  { "PlayingAction", 5 },
  { "PlayingPost", 6 },
  { "PlayingPre", 4 },
  { "Prepared", 3 },
  { "Stopped", 1 },
};
const ProtobufCEnumDescriptor stack_rpc__v1__cue_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueState",
  "CueState",
  "StackRPC__V1__CueState",
  "StackRPC.v1",
  7,
  stack_rpc__v1__cue_state__enum_values_by_number,
  7,
  stack_rpc__v1__cue_state__enum_values_by_name,
  1,
  stack_rpc__v1__cue_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue stack_rpc__v1__cue_wait_trigger__enum_values_by_number[4] =
{
  { "None", "STACK_RPC__V1__CUE_WAIT_TRIGGER__None", 0 },
  { "Immediate", "STACK_RPC__V1__CUE_WAIT_TRIGGER__Immediate", 1 },
  { "AfterPre", "STACK_RPC__V1__CUE_WAIT_TRIGGER__AfterPre", 2 },
  { "AfterAction", "STACK_RPC__V1__CUE_WAIT_TRIGGER__AfterAction", 3 },
};
static const ProtobufCIntRange stack_rpc__v1__cue_wait_trigger__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex stack_rpc__v1__cue_wait_trigger__enum_values_by_name[4] =
{
  { "AfterAction", 3 },
  { "AfterPre", 2 },
  { "Immediate", 1 },
  { "None", 0 },
};
const ProtobufCEnumDescriptor stack_rpc__v1__cue_wait_trigger__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StackRPC.v1.CueWaitTrigger",
  "CueWaitTrigger",
  "StackRPC__V1__CueWaitTrigger",
  "StackRPC.v1",
  4,
  stack_rpc__v1__cue_wait_trigger__enum_values_by_number,
  4,
  stack_rpc__v1__cue_wait_trigger__enum_values_by_name,
  1,
  stack_rpc__v1__cue_wait_trigger__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
